FROM --platform=linux/amd64 golang:1.23-alpine

RUN apk add curl git

WORKDIR /app 

COPY . .

RUN curl -fLo install.sh https://raw.githubusercontent.com/cosmtrek/air/master/install.sh \
    && chmod +x install.sh && sh install.sh && cp ./bin/air /bin/air

CMD "./entrypoint.sh"
