FROM --platform=linux/amd64 ruby:3.3-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
  build-essential \
  default-libmysqlclient-dev \
  git \
  tzdata \
  unzip \
  nodejs \
  libffi-dev \
  libyaml-dev \
  pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Gemfile ./
RUN bundle install

COPY . .

EXPOSE 3000

CMD ["/bin/sh", "entrypoint.sh"]
